# Generated by Django 3.1.1 on 2020-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=2),
        ),
    ]
