# Generated by Django 3.1.1 on 2020-09-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_managementapp', '0002_auto_20200918_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='school_managementapp.students'),
            preserve_default=False,
        ),
    ]
